### ISSUE TITLE
Error when using medrm with BC.4()

### ISSUE THREAD

**Issue by n-jero** [DoseResponse/medrc#8]
Hi,

I'm working on analyzing dose response data with a clear hormesis effect from a blocked experiment, however, when I set fct = BC.4() I get the following error:

Error in str2lang(x) : <text>:1:18: unexpected ','
1: germination~(time,
                                   ^

Here's an example dataset and my model:

#dataset
time <- c(0,0,0,0,12,12,12,12,24,24,24,24,48,48,48,48,96,96,96,96)
block <- c(1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4)
block <- as.factor(block)
germination <- c(.78,.80,.82,.75,.90,.95,.89,.91,.68,.71,.65,.69,.08,.05,.06,.02,0,0,.01,0)
data <- data.frame(block, time, germination)

#model
m <- medrm(germination ~ time,
           data = data,
           fct = BC.4(),
           random = b + e ~ 1|block)

I haven't been able to find any other mentions of str2lang errors from drc/medrc online. Does medrc support the Brain-Cousens model?  If not, can you point me in the direction of other functions to use for the model? 

Thanks!

**Comment by daniel-gerhard** [comment]
Hi,
Unfortunately, the Brain-Cousens model is not yet implemented in medrc. Still on the to-do list.
The code files meXX.R contain all the available model functions (replace XX with the drc name of a function).
Cheers,
D
